# Generated by Django 4.0.1 on 2022-01-30 12:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articlezone', '0002_rename_components_component_alter_node_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='node',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='son', to='articlezone.node'),
        ),
        migrations.AddField(
            model_name='node',
            name='index_in_father',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='node',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
