# Generated by Django 4.0.1 on 2022-02-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articlezone', '0004_node_components_alter_component_default_params_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='components',
            field=models.ManyToManyField(null=True, related_name='place', to='articlezone.Component'),
        ),
    ]
