# Generated by Django 4.0.1 on 2022-02-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articlezone', '0005_alter_node_components'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='components',
            field=models.ManyToManyField(blank=True, null=True, related_name='place', to='articlezone.Component'),
        ),
    ]
