# Generated by Django 4.0.1 on 2022-03-01 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articlezone', '0006_alter_node_components'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='', null=True)),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Component',
            new_name='Concept',
        ),
        migrations.RemoveField(
            model_name='node',
            name='components',
        ),
        migrations.AddField(
            model_name='node',
            name='concepts',
            field=models.ManyToManyField(blank=True, null=True, related_name='place', to='articlezone.Concept'),
        ),
    ]
