# Generated by Django 4.0.1 on 2022-03-05 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articlezone', '0009_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='Resource',
        ),
    ]
