# Generated by Django 4.0.3 on 2022-11-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articlezone', '0018_alter_concept_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='cache',
            field=models.TextField(blank=True, default=''),
        ),
    ]
