# Generated by Django 4.0.3 on 2022-11-02 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articlezone', '0020_auto_20221102_0201'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Concept',
        ),

    ]
