# Generated by Django 4.0.3 on 2022-11-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articlezone', '0021_auto_20221102_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='concepts',
            field=models.TextField(blank=True, default=''),
        ),
    ]
