# Generated by Django 4.0.3 on 2022-11-07 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articlezone', '0022_node_concepts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='concept_def',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='node', to='articlezone.concept'),
        ),
    ]
