# Generated by Django 4.0.3 on 2022-11-07 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articlezone', '0023_concept_node_concept_def'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='concepts',
        ),
    ]
