# Generated by Django 4.1.5 on 2023-03-06 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articlezone', '0024_remove_node_concepts'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='indiscriminate_consumer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='node',
            name='indiscriminate_provider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='node',
            name='tldr',
            field=models.TextField(blank=True, default=''),
        ),
    ]
