# Generated by Django 4.1.5 on 2023-03-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articlezone', '0025_node_indiscriminate_consumer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='tldr_updatetime',
            field=models.IntegerField(default=0),
        ),
    ]
