# Generated by Django 4.1.5 on 2023-03-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articlezone', '0026_node_tldr_updatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='tldr',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
