# Generated by Django 4.1.5 on 2023-07-09 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articlezone', '0027_alter_node_tldr'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_id', models.IntegerField(default=-1)),
                ('linkto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenced_by', to='articlezone.conceptinstance')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_instants', to='articlezone.node')),
            ],
        ),
    ]
