# Generated by Django 4.1.5 on 2023-07-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articlezone', '0028_conceptinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptinstance',
            name='concept_id',
            field=models.IntegerField(default=0),
        ),
    ]
