# Generated by Django 4.1.5 on 2024-06-09 19:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articlezone', '0030_node_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('action', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
