# Generated by Django 4.1.5 on 2024-06-09 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articlezone', '0031_inspectorlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectorlog',
            name='action',
        ),
        migrations.RemoveField(
            model_name='inspectorlog',
            name='time',
        ),
        migrations.AddField(
            model_name='inspectorlog',
            name='date',
            field=models.DateField(default=datetime.date(2024, 6, 9)),
        ),
    ]
