# Generated by Django 4.1.5 on 2024-06-09 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articlezone', '0032_remove_inspectorlog_action_remove_inspectorlog_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectorlog',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
