# Generated by Django 2.1.2 on 2018-11-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Universe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='md',
            name='file',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
