# Generated by Django 2.1.2 on 2019-02-19 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Universe', '0002_md_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Md',
        ),
    ]
