# Generated by Django 2.1.2 on 2019-10-02 11:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='言论',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('内容', models.TextField(default='')),
                ('留言者称呼', models.CharField(default='匿名', max_length=200)),
                ('留言者邮箱', models.CharField(blank=True, max_length=200)),
                ('创建时间', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='讨论_界面模板',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('名', models.CharField(max_length=200)),
                ('位置', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='讨论区',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('名', models.CharField(max_length=200)),
                ('地址', models.CharField(blank=True, default='', max_length=200)),
                ('最低访问等级需求', models.IntegerField(default=0)),
                ('模板', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Open_Discuss_Zone.讨论_界面模板')),
            ],
        ),
        migrations.CreateModel(
            name='话题',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('名', models.TextField(default='')),
                ('讨论区', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='话题', to='Open_Discuss_Zone.讨论区')),
            ],
        ),
        migrations.AddField(
            model_name='言论',
            name='话题',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='言论', to='Open_Discuss_Zone.话题'),
        ),
    ]
