# Generated by Django 2.1.2 on 2019-10-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Open_Discuss_Zone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='话题',
            name='地址',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
