# Generated by Django 2.1.2 on 2019-10-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Open_Discuss_Zone', '0002_话题_地址'),
    ]

    operations = [
        migrations.RenameField(
            model_name='讨论_界面模板',
            old_name='位置',
            new_name='讨论区模板位置',
        ),
        migrations.AddField(
            model_name='讨论_界面模板',
            name='话题模板位置',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
