# Generated by Django 2.1.2 on 2019-10-02 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Open_Discuss_Zone', '0003_auto_20191002_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='话题',
            name='模板',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Open_Discuss_Zone.讨论_界面模板'),
        ),
    ]
