# Generated by Django 2.1.2 on 2019-10-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Open_Discuss_Zone', '0005_auto_20191002_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='讨论区',
            name='朋友',
            field=models.ManyToManyField(to='Open_Discuss_Zone.讨论区'),
        ),
    ]
