# Generated by Django 2.1.2 on 2020-02-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Open_Discuss_Zone', '0006_讨论区_朋友'),
    ]

    operations = [
        migrations.AlterField(
            model_name='讨论区',
            name='朋友',
            field=models.ManyToManyField(blank=True, to='Open_Discuss_Zone.讨论区'),
        ),
    ]
