# Generated by Django 2.1.2 on 2020-02-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='页',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('名', models.CharField(blank=True, default='', max_length=200)),
                ('地址', models.CharField(blank=True, default='', max_length=200)),
                ('最低访问等级需求', models.IntegerField(default=0)),
                ('内容', models.TextField(blank=True, default='')),
            ],
        ),
    ]
