# Generated by Django 2.1.2 on 2020-02-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Free_Page_Zone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='页',
            name='类型',
            field=models.IntegerField(choices=[(0, 'html'), (1, 'python')], default=0),
        ),
    ]
