# Generated by Django 2.1.2 on 2020-02-05 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Free_Page_Zone', '0002_ye_leixing'),
    ]

    operations = [
        migrations.CreateModel(
            name='页文件',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('名', models.CharField(blank=True, default='', max_length=200)),
                ('内容', models.TextField(blank=True, default='')),
                ('父', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='页文件', to='Free_Page_Zone.页')),
            ],
        ),
    ]
