# Generated by Django 2.1.2 on 2018-10-29 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='文章',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('名', models.TextField()),
                ('地址', models.TextField()),
                ('模板名', models.TextField()),
                ('内容', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='页',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('名', models.TextField()),
                ('地址', models.TextField()),
                ('模板文件夹', models.TextField()),
                ('模板名', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='文章',
            name='父页面',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Article_Zone.页'),
        ),
    ]
