# Generated by Django 2.1.2 on 2019-06-04 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Zone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='节点',
            name='额外样式',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='节点',
            name='模板',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Article_Zone.界面模板'),
        ),
    ]
