# Generated by Django 2.1.2 on 2018-10-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Zone', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='页',
            old_name='模板名',
            new_name='列表视图模板名',
        ),
        migrations.AddField(
            model_name='页',
            name='文章视图模板名',
            field=models.TextField(default='e'),
            preserve_default=False,
        ),
    ]
