# Generated by Django 2.1.2 on 2019-10-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Zone', '0002_auto_20190604_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='节点',
            name='名',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
