# Generated by Django 3.0.3 on 2020-06-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Zone', '0003_auto_20191002_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='节点',
            name='界面强化标签',
        ),
        migrations.RemoveField(
            model_name='节点',
            name='额外样式',
        ),
        migrations.AlterField(
            model_name='节点',
            name='内容类型',
            field=models.IntegerField(choices=[(0, 'html（Django模板）'), (1, 'pdf')], default=0),
        ),
    ]
