# Generated by Django 2.1.2 on 2018-11-10 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Zone', '0003_remove_文章_模板名'),
    ]

    operations = [
        migrations.AlterField(
            model_name='文章',
            name='内容',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='文章',
            name='名',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='文章',
            name='地址',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='页',
            name='列表视图模板名',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='页',
            name='名',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='页',
            name='地址',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='页',
            name='文章视图模板名',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='页',
            name='模板文件夹',
            field=models.CharField(max_length=200),
        ),
    ]
