# Generated by Django 2.1.2 on 2018-12-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Zone', '0004_auto_20181110_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='文章',
            old_name='内容',
            new_name='内内容',
        ),
        migrations.AddField(
            model_name='文章',
            name='文章类型',
            field=models.CharField(default='html', max_length=20),
        ),
    ]
