# Generated by Django 3.1.2 on 2021-04-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Zone', '0005_auto_20210418_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='附加',
            name='类型',
            field=models.IntegerField(choices=[(0, 'HTML'), (1, 'Python')], default=0),
        ),
    ]
