# Generated by Django 2.1.2 on 2018-12-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Zone', '0005_auto_20181207_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='文章',
            name='内容',
            field=models.TextField(default=''),
        ),
    ]
