# Generated by Django 2.1.2 on 2018-12-07 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Zone', '0006_文章_内容'),
    ]

    operations = [
        migrations.RenameField(
            model_name='文章',
            old_name='文章类型',
            new_name='类型',
        ),
        migrations.RemoveField(
            model_name='文章',
            name='内内容',
        ),
    ]
