# Generated by Django 2.1.2 on 2018-12-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Zone', '0007_auto_20181207_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='文章',
            name='地址',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='文章',
            name='类型',
            field=models.CharField(default='html', max_length=50),
        ),
        migrations.AlterField(
            model_name='页',
            name='列表视图模板名',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='页',
            name='地址',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='页',
            name='文章视图模板名',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='页',
            name='模板文件夹',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
