# Generated by Django 2.1.2 on 2019-02-19 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Zone', '0008_auto_20181207_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='集',
            fields=[
                ('名', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('地址', models.CharField(blank=True, default='', max_length=200)),
                ('封面模板位置', models.CharField(blank=True, default='', max_length=200)),
                ('封底模板位置', models.CharField(blank=True, default='', max_length=200)),
                ('内容', models.TextField(default='')),
                ('父', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Article_Zone.集')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='文章',
            name='id',
        ),
        migrations.RemoveField(
            model_name='文章',
            name='父页面',
        ),
        migrations.AddField(
            model_name='文章',
            name='模板位置',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='文章',
            name='父',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Article_Zone.文章'),
        ),
        migrations.AlterField(
            model_name='文章',
            name='名',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='页',
        ),
    ]
