# Generated by Django 2.1.2 on 2019-02-19 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Zone', '0009_auto_20190220_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='文章',
            name='父',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Article_Zone.文章'),
        ),
        migrations.AlterField(
            model_name='集',
            name='父',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Article_Zone.集'),
        ),
    ]
