# Generated by Django 2.1.2 on 2019-02-19 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Zone', '0010_auto_20190220_0047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='集',
            old_name='父',
            new_name='父集',
        ),
        migrations.RemoveField(
            model_name='文章',
            name='父',
        ),
        migrations.AddField(
            model_name='文章',
            name='父集',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Article_Zone.集'),
        ),
    ]
