# Generated by Django 2.1.2 on 2019-02-19 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Zone', '0011_auto_20190220_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='节点',
            fields=[
                ('名', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('地址', models.CharField(blank=True, default='', max_length=200)),
                ('封面模板位置', models.CharField(blank=True, default='', max_length=200)),
                ('封底模板位置', models.CharField(blank=True, default='', max_length=200)),
                ('内容类型', models.CharField(default='html', max_length=200)),
                ('内容', models.TextField(default='')),
                ('父', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Article_Zone.节点')),
            ],
        ),
        migrations.RemoveField(
            model_name='文章',
            name='父集',
        ),
        migrations.RemoveField(
            model_name='集',
            name='父集',
        ),
        migrations.DeleteModel(
            name='文章',
        ),
        migrations.DeleteModel(
            name='集',
        ),
    ]
