# Generated by Django 2.1.2 on 2019-02-19 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Zone', '0012_auto_20190220_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='节点',
            name='父',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='子', to='Article_Zone.节点'),
        ),
    ]
