# Generated by Django 2.1.2 on 2019-02-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Zone', '0013_auto_20190220_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='节点',
            name='节点类型',
            field=models.IntegerField(choices=[(0, '文章'), (1, '集')], default=0, max_length=200),
        ),
    ]
