# Generated by Django 2.1.2 on 2019-02-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Zone', '0014_节点_节点类型'),
    ]

    operations = [
        migrations.AlterField(
            model_name='节点',
            name='封面模板位置',
            field=models.CharField(blank=True, default='default.html', max_length=200),
        ),
        migrations.AlterField(
            model_name='节点',
            name='节点类型',
            field=models.IntegerField(choices=[(0, '文章'), (1, '集')], default=0),
        ),
    ]
