# Generated by Django 2.1.2 on 2019-02-20 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Zone', '0015_auto_20190220_0222'),
    ]

    operations = [
        migrations.CreateModel(
            name='留言',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('内容', models.TextField(default='')),
                ('对象', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Article_Zone.节点')),
            ],
        ),
    ]
