# Generated by Django 2.1.2 on 2019-02-20 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Zone', '0016_留言'),
    ]

    operations = [
        migrations.AddField(
            model_name='留言',
            name='留言者称呼',
            field=models.CharField(default='匿名', max_length=200),
        ),
        migrations.AddField(
            model_name='留言',
            name='留言者邮箱',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='留言',
            name='对象',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='留言', to='Article_Zone.节点'),
        ),
    ]
