# Generated by Django 2.1.2 on 2019-02-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Zone', '0017_auto_20190220_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='节点',
            name='内容类型',
            field=models.IntegerField(choices=[(0, 'html'), (1, 'txt'), (2, 'md')], default=0),
        ),
    ]
