# Generated by Django 2.1.2 on 2019-02-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Zone', '0018_auto_20190221_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='节点',
            name='内容',
            field=models.TextField(blank=True, default=''),
        ),
    ]
