# Generated by Django 2.1.2 on 2019-02-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Zone', '0020_auto_20190221_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='节点',
            name='id',
        ),
        migrations.AlterField(
            model_name='节点',
            name='名',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
