# Generated by Django 2.1.2 on 2019-02-21 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Zone', '0021_auto_20190221_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='留言',
            name='对象',
        ),
    ]
