# Generated by Django 2.1.2 on 2019-02-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Zone', '0022_remove_留言_对象'),
    ]

    operations = [
        migrations.AddField(
            model_name='节点',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='节点',
            name='名',
            field=models.CharField(max_length=200),
        ),
    ]
