# Generated by Django 2.1.2 on 2019-02-21 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Zone', '0023_auto_20190221_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='留言',
            name='对象',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='留言', to='Article_Zone.节点'),
            preserve_default=False,
        ),
    ]
