# Generated by Django 2.1.2 on 2019-02-23 08:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Zone', '0026_auto_20190221_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='留言',
            name='创建时间',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='节点',
            name='创建时间',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='节点',
            name='最后修改时间',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
