# Generated by Django 2.1.2 on 2019-02-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Zone', '0027_auto_20190223_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='节点',
            name='最低访问权限',
            field=models.IntegerField(default=0),
        ),
    ]
