# Generated by Django 2.1.2 on 2019-02-23 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Zone', '0028_节点_最低访问权限'),
    ]

    operations = [
        migrations.RenameField(
            model_name='节点',
            old_name='最低访问权限',
            new_name='最低访问等级需求',
        ),
    ]
