# Generated by Django 2.1.2 on 2019-02-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Zone', '0029_auto_20190223_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='节点',
            name='内容类型',
            field=models.IntegerField(choices=[(0, 'html（Django模板）'), (3, 'html（非Django模板）'), (1, 'txt'), (2, 'md')], default=0),
        ),
    ]
