# Generated by Django 2.1.2 on 2019-02-24 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Zone', '0030_auto_20190223_1724'),
    ]
