# Generated by Django 2.1.2 on 2019-02-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Zone', '0030_auto_20190223_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='文章文件',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
