# Generated by Django 2.1.2 on 2019-02-24 04:56

from django.db import migrations
import simditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Zone', '0030_auto_20190223_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='节点',
            name='内容',
            field=simditor.fields.RichTextField(blank=True, default=''),
        ),
    ]
