# Generated by Django 2.1.2 on 2019-02-25 04:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Zone', '0031_auto_20190224_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='节点',
            name='内容',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
    ]
