# Generated by Django 2.1.2 on 2019-02-23 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Zone', '0031_文章文件'),
    ]

    operations = [
        migrations.DeleteModel(
            name='文章文件',
        ),
    ]
