# Generated by Django 2.1.2 on 2019-02-25 05:05

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Zone', '0032_auto_20190225_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='节点',
            name='内容',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=''),
        ),
    ]
