# Generated by Django 2.1.2 on 2019-02-23 11:48

import Article_Zone.utils.deal_file
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Zone', '0032_delete_文章文件'),
    ]

    operations = [
        migrations.CreateModel(
            name='文章文件',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('文件', models.FileField(upload_to=Article_Zone.utils.deal_file.get_file_name)),
                ('目标文章', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Article_Zone.节点')),
            ],
        ),
    ]
