# Generated by Django 2.1.2 on 2019-02-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Zone', '0033_文章文件'),
    ]

    operations = [
        migrations.AddField(
            model_name='文章文件',
            name='文件名',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
