# Generated by Django 2.1.2 on 2019-02-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Zone', '0033_auto_20190225_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='节点',
            name='排序依据',
            field=models.IntegerField(default=0),
        ),
    ]
