# Generated by Django 2.1.2 on 2019-03-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Zone', '0034_节点_排序依据'),
    ]

    operations = [
        migrations.AlterField(
            model_name='节点',
            name='封面模板位置',
            field=models.CharField(blank=True, default='/default/default.html', max_length=200),
        ),
    ]
