# Generated by Django 2.1.2 on 2019-02-23 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Zone', '0034_文章文件_文件名'),
    ]

    operations = [
        migrations.RenameField(
            model_name='文章文件',
            old_name='目标文章',
            new_name='目标节点',
        ),
    ]
