# Generated by Django 2.1.2 on 2019-02-23 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Zone', '0035_auto_20190223_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='文章文件',
            name='目标节点',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='文件', to='Article_Zone.节点'),
        ),
    ]
