# Generated by Django 2.1.2 on 2019-03-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Zone', '0035_auto_20190302_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='节点',
            name='内容类型',
            field=models.IntegerField(choices=[(0, 'html（Django模板）'), (3, 'html（非Django模板）'), (1, 'txt'), (2, 'md'), (4, 'pdf')], default=0),
        ),
    ]
