# Generated by Django 2.1.2 on 2019-03-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Zone', '0036_auto_20190326_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='节点',
            name='强化标签',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
