# Generated by Django 2.1.2 on 2019-03-26 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Zone', '0037_节点_强化标签'),
    ]

    operations = [
        migrations.RenameField(
            model_name='节点',
            old_name='强化标签',
            new_name='界面强化标签',
        ),
    ]
