# Generated by Django 2.1.2 on 2019-05-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Zone', '0038_auto_20190326_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='界面模板',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('名', models.CharField(max_length=200)),
                ('封面位置', models.CharField(max_length=200)),
                ('封底位置', models.CharField(max_length=200)),
            ],
        ),
    ]
