# Generated by Django 2.1.2 on 2019-05-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Zone', '0039_界面模板'),
    ]

    operations = [
        migrations.AlterField(
            model_name='界面模板',
            name='封底位置',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='界面模板',
            name='封面位置',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
