# Generated by Django 2.1.2 on 2019-05-11 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Zone', '0040_auto_20190511_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='节点',
            name='封底模板位置',
        ),
        migrations.RemoveField(
            model_name='节点',
            name='封面模板位置',
        ),
        migrations.AddField(
            model_name='节点',
            name='模板',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Article_Zone.界面模板'),
        ),
    ]
