# Generated by Django 2.1.2 on 2019-05-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='空间',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('名', models.CharField(max_length=200)),
                ('位置', models.CharField(max_length=200)),
                ('地址', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='访问者',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('名', models.CharField(max_length=200)),
                ('访问等级', models.IntegerField(default=0)),
                ('密码', models.CharField(blank=True, max_length=200)),
                ('IP地址', models.CharField(max_length=200)),
                ('进入时间', models.BigIntegerField(default=0)),
                ('停留时间', models.IntegerField(default=1800)),
                ('cookie_value', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
