# Generated by Django 2.1.2 on 2018-11-10 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Zone',
            new_name='空间',
        ),
    ]
