# Generated by Django 2.1.2 on 2018-11-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0002_auto_20181110_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='空间',
            name='位置',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='空间',
            name='名',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='空间',
            name='地址',
            field=models.CharField(max_length=200),
        ),
    ]
