# Generated by Django 2.1.2 on 2018-11-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0003_auto_20181110_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='用户',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('名', models.CharField(max_length=200)),
                ('密码', models.CharField(max_length=200)),
            ],
        ),
    ]
