# Generated by Django 2.1.2 on 2018-11-25 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0004_用户'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='用户',
            new_name='访问者',
        ),
    ]
