# Generated by Django 2.1.2 on 2018-11-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0005_auto_20181125_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='访问者',
            name='密码',
            field=models.CharField(default='', max_length=200),
        ),
    ]
