# Generated by Django 2.1.2 on 2018-11-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0006_auto_20181125_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='访问者',
            name='密码',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
