# Generated by Django 2.1.2 on 2018-11-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0007_auto_20181125_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='访问者',
            name='名',
        ),
        migrations.RemoveField(
            model_name='访问者',
            name='密码',
        ),
        migrations.AddField(
            model_name='访问者',
            name='权限等级',
            field=models.CharField(default='q', max_length=20),
            preserve_default=False,
        ),
    ]
