# Generated by Django 2.1.2 on 2018-11-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0008_auto_20181125_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='访问者',
            name='IP地址',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='访问者',
            name='密码',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
