# Generated by Django 2.1.2 on 2018-11-25 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0010_auto_20181125_2253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='访问者',
        ),
    ]
