# Generated by Django 2.1.2 on 2018-12-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0012_访问者'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='访问者',
            name='停留时间',
        ),
        migrations.AlterField(
            model_name='访问者',
            name='访问时间',
            field=models.DateTimeField(),
        ),
    ]
