# Generated by Django 2.1.2 on 2018-12-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0013_auto_20181207_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='访问者',
            name='停留时间',
            field=models.IntegerField(default=1800),
        ),
        migrations.AlterField(
            model_name='访问者',
            name='访问时间',
            field=models.IntegerField(default=1544179436),
        ),
    ]
