# Generated by Django 2.1.2 on 2018-12-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0014_auto_20181207_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='访问者',
            name='访问时间',
            field=models.IntegerField(default=0),
        ),
    ]
