# Generated by Django 2.1.2 on 2018-12-07 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0016_auto_20181207_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='访问者',
            name='停留时间',
        ),
    ]
