# Generated by Django 2.1.2 on 2018-12-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0017_remove_访问者_停留时间'),
    ]

    operations = [
        migrations.AddField(
            model_name='访问者',
            name='停留时间',
            field=models.IntegerField(default=1800),
        ),
    ]
