# Generated by Django 2.1.2 on 2018-12-07 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0018_访问者_停留时间'),
    ]

    operations = [
        migrations.RenameField(
            model_name='访问者',
            old_name='访问时间',
            new_name='进入时间',
        ),
    ]
