# Generated by Django 2.1.2 on 2019-02-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0019_auto_20181207_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='访问者',
            name='权限等级',
        ),
        migrations.AddField(
            model_name='访问者',
            name='名',
            field=models.CharField(default='?', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='访问者',
            name='访问等级',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='访问者',
            name='IP地址',
            field=models.CharField(max_length=200),
        ),
    ]
