# Generated by Django 2.1.2 on 2019-04-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0020_auto_20190223_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='访问者',
            name='cookie_value',
            field=models.CharField(default='', max_length=200),
        ),
    ]
